name: Node.js CI

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test

      - name: Compute and Print Secret Keys
        run: |
          BRANCH_NAME_UPPER=$(echo '${{ github.ref_name }}' | tr '[:lower:]' '[:upper:]')
          DATABASE_URL_KEY="${BRANCH_NAME_UPPER}_DATABASE_URL"
          DATABASE_URL_UNPOOLED_KEY="${BRANCH_NAME_UPPER}_DATABASE_URL_UNPOOLED"
          echo "Computed Key for Pooled URL: $DATABASE_URL_KEY"
          echo "Computed Key for Unpooled URL: $DATABASE_URL_UNPOOLED_KEY"
        shell: bash

      - name: Print Secrets for Debug
        if: github.ref != 'refs/heads/main'
        env:
          BRANCH_NAME_UPPER: ${{ github.ref_name }}
        run: |
          echo "Placeholder for Database URL Pooled: ${{ secrets[format('{0}_DATABASE_URL', github.ref_name | upper)] }}"
          echo "Placeholder for Database URL Unpooled: ${{ secrets[format('{0}_DATABASE_URL_UNPOOLED', github.ref_name | upper)] }}"
        shell: bash
