name: Node.js CI

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Construct and Print Secret Name
        if: github.ref != 'refs/heads/main'
        id: get_secret
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME_UPPER=$(echo $BRANCH_NAME | tr '[:lower:]' '[:upper:]')
          SECRET_NAME="${BRANCH_NAME_UPPER}_DATABASE_URL"
          echo "::set-output name=secret_command::echo 'DATABASE_URL=\${{ secrets.$SECRET_NAME }}'"
      - name: Use the Secret
        if: github.ref != 'refs/heads/main'
        run: |
          $( ${{ steps.get_secret.outputs.secret_command }} )
          echo "Using Database URL: $DATABASE_URL"
