name: Node.js CI

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]  # Updated Node version to 20.x

    steps:
      - name: Check Node.js version
        run: node -v

      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test

      - name: Set uppercase branch name
        id: set_upper_branch
        run: |
          echo "BRANCH_NAME=$(echo '${{ github.ref_name }}' | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
          echo "UPPER_BRANCH_NAME=${BRANCH_NAME}_DATABASE_URL" >> $GITHUB_ENV
          echo "UPPER_BRANCH_NAME_UNPOOLED=${BRANCH_NAME}_DATABASE_URL_UNPOOLED" >> $GITHUB_ENV

      - name: Print Environment Secrets
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Database URL Pooled: ${{ secrets[env.UPPER_BRANCH_NAME] }}"
          echo "Database URL Unpooled: ${{ secrets[env.UPPER_BRANCH_NAME_UNPOOLED] }}"
