name: Node.js CI

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]  # Updated Node version to 20.x

    steps:
      - name: Check Node.js version
        run: node -v

      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test

      - name: Debug and Print Environment Secrets
        if: github.ref != 'refs/heads/main'
        run: |
          BRANCH_NAME_UPPER=$(echo '${{ github.ref_name }}' | tr '[:lower:]' '[:upper:]')
          echo "Computed Key for Pooled URL: ${BRANCH_NAME_UPPER}_DATABASE_URL"
          echo "Computed Key for Unpooled URL: ${BRANCH_NAME_UPPER}_DATABASE_URL_UNPOOLED"
          echo "Database URL Pooled: ${{ secrets[format('{0}_DATABASE_URL', BRANCH_NAME_UPPER)] }}"
          echo "Database URL Unpooled: ${{ secrets[format('{0}_DATABASE_URL_UNPOOLED', BRANCH_NAME_UPPER)] }}"
        shell: bash
