name: Node.js CI

on:
  push:
    branches:
      - '*'  # Trigger on every branch

jobs:
  build:
    runs-on: ubuntu-latest
    # Conditional environment setting
    environment: ${{ (github.ref_name == 'main' && 'NEON_PREVIEW_PROD') || 'NEON_PREVIEW_ENV' }}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract and echo branch name
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '[:lower:]' '[:upper:]' | tr -d '-')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Normalized Branch Name: $BRANCH_NAME"
        shell: bash


      - name: Debug secret key
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            SECRET_KEY="DATABASE_URL"
          else
            SECRET_KEY="${{ env.BRANCH_NAME }}_DATABASE_URL"
          fi
          echo "Secret Key for DB URL: $SECRET_KEY"
          echo "SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV
        shell: bash

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          DATABASE_URL: ${{ secrets[env.SECRET_KEY] }}

      - name: Build
        run: |
          npm run build --if-present
        env:
          DATABASE_URL: ${{ secrets[env.SECRET_KEY] }}

      - name: Run tests
        run: |
          echo "SECRET_KEY: $SECRET_KEY"
          echo "${DATABASE_URL}"
          npm test
        env:
          DATABASE_URL: ${{ secrets[env.SECRET_KEY] }}
