name: Node.js CI

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
#      - run: npm ci
#      - run: npm run build --if-present
#      - run: npm test
      - name: Set up branch specific DATABASE_URL
        if: github.ref != 'refs/heads/main'
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          BRANCH_NAME_UPPER=$(echo "$BRANCH_NAME" | tr '[:lower:]' '[:upper:]')
          SECRET_ENV_VAR_NAME="${BRANCH_NAME_UPPER}_DATABASE_URL"
          DATABASE_URL_VAR=$(printenv $SECRET_ENV_VAR_NAME)
          echo "Using Database URL: $DATABASE_URL_VAR"
